spring:
  main:
    web-application-type: none
    lazy-initialization: true

output:
  data-output-directory: "./output"

machine-box:
  tag-box:
    endpoint: "http://localhost:80/tagbox"
    state-file: "./config/tagbox.state"
    blacklist: []
  face-box:
    endpoint: "http://localhost:80/facebox"
    state-file: "./config/facebox.state"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{0}: %msg%n"
  level:
    nl.juraji.ml.imageScanner.MlImageScannerApplicationKt: ERROR