apiVersion: v1
kind: Secret
metadata:
  name: machinebox-secret
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  MB_KEY: {{ .Values.mbKey | b64enc }}